pid /home/runner/nginx.pid;

worker_processes auto;
daemon off; 

error_log /home/runner/logs/error.log; 

events {
    worker_connections 1024;
}

http {
    include /home/runner/mime.types;
    default_type application/octet-stream;
    
    access_log /home/runner/logs/access.log; 
    
    client_body_temp_path /home/runner/nginx_tmp/body;
    fastcgi_temp_path     /home/runner/nginx_tmp/fastcgi;
    proxy_temp_path       /home/runner/nginx_tmp/proxy;
    scgi_temp_path        /home/runner/nginx_tmp/scgi;
    uwsgi_temp_path       /home/runner/nginx_tmp/uwsgi;
    
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080; 

        set $vllm_upstream http://127.0.0.1:8081; 

        location /health-check {
            proxy_pass $vllm_upstream/v1/models;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass $vllm_upstream;
            proxy_set_header Host $host;
        }
    }
}