FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ENV HOME=/home/runner
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_NO_CACHE=1

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="${VIRTUAL_ENV}/bin:$HOME/.local/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV HF_HOME=/app
ENV TORCH_HOME=/app

SHELL [ "/bin/bash", "-c" ]

RUN <<eot
    set -ex
    apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-venv \
        libgomp1 \
        ffmpeg \
        && rm -rf /var/lib/apt/lists/*
    
    # Security: add user runner
    useradd --uid 10000 runner
    mkdir /home/runner && chown runner /home/runner
    mkdir -p /app && chown runner /app
    
    # Security: disable root login
    passwd -l root
eot

COPY --from=ghcr.io/astral-sh/uv:0.8.22 /uv /uvx $HOME/.local/bin/

USER runner

WORKDIR /app

EXPOSE 8080

RUN uv venv ${VIRTUAL_ENV}

RUN --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  uv sync --frozen --no-install-project --no-dev --active

COPY --chown=runner:runner . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
